// src/pages/settings/badges/badges.jsx
import classNames from 'classnames/bind';
import React, { useEffect, useState } from 'react';
import { CopyToClipboard } from 'react-copy-to-clipboard';
import { useParams } from 'react-router-dom';

import { instance } from '_constants';
import Button from 'components/shared/button';
import Form, { Field } from 'components/shared/form';
import { ReactComponent as CopyIcon } from 'svg/copy.svg';

import styles from './badges.module.scss';

const cx = classNames.bind(styles);

const BADGE_OPTIONS = [
  {
    key: 'Markdown',
    value: 'markdown',
  },
  {
    key: 'Markup',
    value: 'markup',
  },
  {
    key: 'CCMenu',
    value: 'cc',
  },
];

const buildImage = (branch, droneInstance, name, namespace) => {
  const branchSuffix = branch ? `?ref=refs/heads/${branch}` : '';
  return `${droneInstance}/api/badges/${namespace}/${name}/status.svg${branchSuffix}`;
};

const buildSnippet = ({
  syntax, image, namespace, name,
}) => {
  switch (syntax) {
    case 'markup':
      return `<a href="${instance}/${namespace}/${name}">
  <img src="${image}" />
</a>`;
    case 'cc':
      return `${instance}/${namespace}/${name}/cc.xml`;
    case 'markdown':
    default:
      return `[![Build Status](${image})](${instance}/${namespace}/${name})`;
  }
};

export default function Main() {
  const { namespace, name } = useParams();
  const [isSnippetCopied, setIsSnippetCopied] = useState(false);

  /* States */
  const [badge, setBadge] = useState({ branch: '', snippetSyntax: 'markdown' });
  // derived state
  const image = buildImage(badge.branch, instance, name, namespace);

  const handleBadgeBranchChange = ({ target }) => {
    setBadge((prev) => ({ ...prev, branch: target.value.trim() }));
  };

  const handleBadgeSyntaxChange = ({ target }) => {
    setBadge((prev) => ({ ...prev, snippetSyntax: target.value }));
  };

  const handleCopyClick = () => {
    setIsSnippetCopied(true);
  };

  useEffect(() => {
    let timeout;
    if (isSnippetCopied) {
      timeout = setTimeout(() => {
        setIsSnippetCopied(false);
      }, 2000);
    }
    return () => clearTimeout(timeout);
  }, [isSnippetCopied]);

  useEffect(() => {
    setIsSnippetCopied(false);
  }, [badge]);

  return (
    <div className={cx('wrapper')}>
      <div className={cx('inner')}>
        <img alt="badge" src={image} />
        <Form className={cx('group')}>
          <div className={cx('group', 'group-badge')}>
            <Field.Select
              label="Syntax"
              name="syntax"
              value={badge.snippetSyntax}
              optionsList={BADGE_OPTIONS}
              width={260}
              onChange={handleBadgeSyntaxChange}
            />
            <Field.Input
              label="Branch"
              name="branch"
              placeholder="master"
              value={badge.branch}
              width={260}
              onChange={handleBadgeBranchChange}
            />
          </div>
          <pre className={cx('badge-snippet')}>
            <CopyToClipboard
              text={badge.snippetSyntax}
              onCopy={handleCopyClick}
            >
              <Button className={cx('copy-btn')} type="button">
                {isSnippetCopied ? 'Copied!' : <CopyIcon />}
              </Button>
            </CopyToClipboard>
            <code>
              {buildSnippet({
                syntax: badge.snippetSyntax, image, namespace, name,
              })}
            </code>
          </pre>
        </Form>
      </div>
    </div>
  );
}

// src/components/Badges.vue
<template>
  <Card>
    <h2 slot="header">Badges</h2>
    <img slot="header" :src="image" alt="badge"/>

    <div class="options">
      <BaseSelect v-model="lang" :options="langs"/>
      <BaseInput v-model="branch" placeholder="master" type="text"/>
    </div>

    <CodeSnippet>
      <code>{{ code }}</code>
    </CodeSnippet>
  </Card>
</template>

<script>
import Card from "@/components/Card.vue";
import CodeSnippet from "@/components/CodeSnippet.vue";
import BaseSelect from "@/components/forms/BaseSelect.vue";
import BaseInput from "@/components/forms/BaseInput.vue";

export default {
  name: "badges",
  components: {
    Card,
    CodeSnippet,
    BaseSelect,
    BaseInput
  },
  data() {
    return {
      langs,
      lang: "markdown",
      branch: undefined
    };
  },
  computed: {
    instance() {
      return this.$store.state.instance.url;
    },
    name() {
      return this.$route.params.namespace + "/" + this.$route.params.name;
    },
    image() {
      const branchSuffix = this.branch ? `?ref=/refs/heads/${this.branch}` : "";
      return `${this.instance}/api/badges/${this.name}/status.svg${branchSuffix}`;
    },
    code() {
      switch (this.lang) {
        case "markdown":
          return `[![Build Status](${this.image})](${this.instance}/${this.name})`;
        case "markup":
          return `<a href="${this.instance}/${this.name}"><img src="${this.image}" /></a>`;
        case "ccmenu":
          return `${this.instance}/api/badges/${this.name}/cc.xml`;
      }
    }
  }
};

const langs = [["markdown", "Markdown"], ["markup", "Markup"], ["ccmenu", "CCMenu"]];
</script>

<style scoped lang="scss">
@import "../assets/styles/mixins";

.header {
  display: flex;
  align-items: center;
}

h2 {
  flex-grow: 1;
}

.options {
  display: flex;
  margin-bottom: 20px;

  @include tablet {
    flex-direction: column;
  }
}

.options select {
  flex-basis: 220px;
  margin-right: 20px;

  @include tablet {
    width: 100%;
    flex-basis: auto;
    margin-bottom: 15px;
  }
}

.options input {
  flex-grow: 1;

  @include tablet {
    width: 100%;
  }
}
</style>
