// src/components/Footer.vue
<template>
  <footer>
    <nav>
        <a target="_blank" href="https://readme.drone.io">Documentation</a>
        <a target="_blank" href="http://plugins.drone.io">Plugins</a>
        <a target="_blank" href="https://discourse.drone.io">Support</a>
    </nav>
    <nav>
        <a target="_blank" href="https://github.com/drone">GitHub</a>
        <a target="_blank" href="https://twitter.com/droneio">Twitter</a>
        <a target="_blank" href="https://discourse.drone.io">Discourse</a>
        <a target="_blank" href="https://gitter.im/drone/drone">Gitter</a>
    </nav>
  </footer>
</template>

<style scoped>
footer {
  display: flex;
  justify-content: space-between;
  padding: 0 30px;
  align-items: center;
}

nav a {
  color: rgba(25, 45, 70, 0.6);
}

nav a:hover,
nav a:focus {
  color: #192d46;
  outline: none;
}

nav a + a {
  margin-left: 30px;
}
</style>

// src/components/shared/footer/footer.jsx
import classNames from 'classnames/bind';
import React from 'react';

import styles from './footer.module.scss';

const cx = classNames.bind(styles);

const LEFT_SIDE_ITEMS = [
  {
    label: 'Documentation',
    link: 'https://readme.drone.io/',
  },
  {
    label: 'Plugins',
    link: 'http://plugins.drone.io/',
  },
  {
    label: 'Support',
    link: 'https://discourse.drone.io/',
  },
];

const RIGHT_SIDE_ITEMS = [
  {
    label: 'GitHub',
    link: 'https://github.com/drone',
  },
  {
    label: 'Twitter',
    link: 'https://twitter.com/droneio',
  },
  {
    label: 'Discourse',
    link: 'https://discourse.drone.io/',
  },
  {
    label: 'Gitter',
    link: 'https://gitter.im/drone/drone',
  },
];

export default function Footer() {
  return (
    <footer className={cx('container', 'footer')}>
      <nav>
        {LEFT_SIDE_ITEMS.map(({ label, link }) => (
          <a key={link} href={link} target="_blank" rel="noopener noreferrer">{label}</a>
        ))}
      </nav>
      <nav>
        {RIGHT_SIDE_ITEMS.map(({ label, link }) => (
          <a key={link} href={link} target="_blank" rel="noopener noreferrer">{label}</a>
        ))}
      </nav>
    </footer>
  );
}
