// src/views/Account.vue
<template>
  <div class="account">
    <header>
      <h1>User Settings</h1>
    </header>

    <CardGroup v-if="user && user.token">
      <Card>
        <header slot="header">
          <h2>Token</h2>
        </header>

        <CodeSnippetGroup>
          <CodeSnippet>
            <h3 slot="header">Your Personal Token:</h3>
            <pre>
              <code>{{ user.token }}</code>  
            </pre>
          </CodeSnippet>

          <CodeSnippet>
            <h3 slot="header">Example API Usage:</h3>
            <pre class="terminal single-command">
              <code>curl -i {{ instance }}/api/user \</code>
              <code>-H "Authorization: Bearer {{ user.token }}"</code>
            </pre>
          </CodeSnippet>

          <CodeSnippet>
            <h3 slot="header">Example CLI Usage:</h3>
            <pre class="terminal">
              <code>export DRONE_SERVER={{ instance }}</code>
              <code>export DRONE_TOKEN={{user.token}}</code> 
              <code>drone info</code>  
            </pre>
          </CodeSnippet>
        </CodeSnippetGroup>
      </Card>
    </CardGroup>
  </div>
</template>

<script>
import Card from "@/components/Card.vue";
import CardGroup from "@/components/CardGroup.vue";
import CodeSnippet from "@/components/CodeSnippet.vue";
import CodeSnippetGroup from "@/components/CodeSnippetGroup.vue";

export default {
  name: "account",
  components: {
    Card,
    CardGroup,
    CodeSnippet,
    CodeSnippetGroup,
  },
  computed: {
    instance() {
      return this.$store.state.instance.url;
    },
    user() {
      return this.$store.state.user;
    }
  }
};
</script>

<style scoped>
h1 {
  height: 41px;
  font-size: 30px;
  font-weight: normal;
  font-style: normal;
  font-stretch: normal;
  line-height: normal;
  letter-spacing: normal;
  color: #192d46;
  margin: 30px 0px;
}
</style>

// src/pages/account/account.jsx
import classNames from 'classnames/bind';
import React, { useLayoutEffect, useState } from 'react';
import { CopyToClipboard } from 'react-copy-to-clipboard';

import { instance } from '_constants';
import Button from 'components/shared/button';
import { useCustomTitle } from 'hooks';
import { useViewerToken } from 'hooks/swr';
import { ReactComponent as CopyIcon } from 'svg/copy.svg';

import css from './account.module.scss';

const cx = classNames.bind(css);

const initialState = {
  token: {
    copied: false,
    snippet: null,
  },
  api: {
    copied: false,
    snippet: null,
  },
  cli: {
    copied: false,
    snippet: null,
  },
};

export default function Account() {
  const [snippets, setSnippets] = useState(initialState);

  const { data } = useViewerToken();

  useCustomTitle('Account');

  const handleCopyClick = (snippetCategory) => () => {
    setSnippets((prev) => ({
      ...prev,
      [snippetCategory]: {
        ...prev[snippetCategory],
        copied: true,
      },
    }));
    setTimeout(() => {
      setSnippets((prev) => ({
        ...prev,
        [snippetCategory]: {
          ...prev[snippetCategory],
          copied: false,
        },
      }));
    }, 2000);
  };

  useLayoutEffect(() => {
    if (data?.token) {
      setSnippets({
        token: {
          copied: false,
          snippet: data.token,
        },
        api: {
          copied: false,
          snippet: [`curl -i ${instance}/api/user`, `-H "Authorization: Bearer ${data.token}"`],
        },
        cli: {
          copied: false,
          snippet: [`export DRONE_SERVER=${instance}`, `export DRONE_TOKEN=${data.token}`, 'drone info'],
        },
      });
    }
  }, [data?.token]);
  return (
    <>
      <header className={cx('header')}>
        <h1>Account Settings</h1>
        <a href="/logout" target="_self">Logout</a>
      </header>
      <section className={cx('wrapper')}>
        {snippets.token.snippet ? (
          <div>
            <div className={cx('row')}>
              <span className={cx('label')}>Your personal token:</span>
              <pre className={cx('snippet')}>
                <CopyToClipboard
                  text={snippets.token.snippet}
                  onCopy={handleCopyClick('token')}
                >
                  <Button
                    className={cx('copy-btn')}
                  >
                    {snippets.token.copied ? 'Copied' : <CopyIcon />}
                  </Button>
                </CopyToClipboard>
                <code>{snippets.token.snippet}</code>
              </pre>
            </div>
            <div className={cx('row')}>
              <span className={cx('label')}>Example API Usage:</span>
              <pre className={cx('snippet')}>
                <CopyToClipboard
                  text={snippets.api.snippet.join('\n')}
                  onCopy={handleCopyClick('api')}
                >
                  <Button
                    className={cx('copy-btn')}
                  >
                    {snippets.api.copied ? 'Copied' : <CopyIcon />}
                  </Button>
                </CopyToClipboard>
                <code>
                  <div>
                    <span>$</span>
                    {snippets.api.snippet[0]}
                  </div>
                  <div>
                    <span>&gt;</span>
                    {snippets.api.snippet[1]}
                  </div>
                </code>
              </pre>
            </div>
            <div className={cx('row')}>
              <span className={cx('label')}>Example CLI Usage:</span>
              <pre className={cx('snippet')}>
                <CopyToClipboard
                  text={snippets.cli.snippet?.join('\n')}
                  onCopy={handleCopyClick('cli')}
                >
                  <Button
                    className={cx('copy-btn')}
                  >
                    {snippets.cli.copied ? 'Copied' : <CopyIcon />}
                  </Button>
                </CopyToClipboard>
                <code>
                  <div>
                    <span>$</span>
                    {snippets.cli.snippet[0]}
                  </div>
                  <div>
                    <span>$</span>
                    {snippets.cli.snippet[1]}
                  </div>
                  <div>
                    <span>$</span>
                    {snippets.cli.snippet[2]}
                  </div>
                </code>
              </pre>
            </div>
          </div>
        ) : null}
      </section>
    </>
  );
}
